/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package stockMarket;
import aos.jack.jak.event.InferenceGoalEvent;

/**
 * 
 */

public class FindAndTellInvesters extends aos.jack.jak.event.InferenceGoalEvent {
    public java.lang.String company;
    public int price;
    public int numberOfShares;
    public java.lang.String seller;
    public java.lang.String buyer;
    private final static java.lang.String[] __eventVariableNames = {
            "company",
            "price",
            "numberOfShares",
            "seller",
            "buyer"};
    private final static java.lang.String[] __eventVariableTypes = {
            "String",
            "int",
            "int",
            "String",
            "String"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public stockMarket.FindAndTellInvesters findAllInvestors(java.lang.String company, int price, int shares, java.lang.String seller)
    {
        stockMarket.FindAndTellInvesters tmp = new stockMarket.FindAndTellInvesters();
        tmp.init(this);
        return tmp.findAllInvestors_body(company,price,shares,seller);
    }
    
    private stockMarket.FindAndTellInvesters findAllInvestors_body(java.lang.String company, int price, int shares, java.lang.String seller)
    {
        this.company = company;
        this.price = price;
        this.numberOfShares = shares;
        this.seller = seller;
        this.buyer = null;
        return this;
    }
    
    public FindAndTellInvesters()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "stockMarket/FindAndTellInvesters.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(company);
            }
            case 1: 
            {
                return aos.util.ToObject.box(price);
            }
            case 2: 
            {
                return aos.util.ToObject.box(numberOfShares);
            }
            case 3: 
            {
                return aos.util.ToObject.box(seller);
            }
            case 4: 
            {
                return aos.util.ToObject.box(buyer);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
