/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package stockMarket;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class HandleSellRequest extends aos.jack.jak.plan.Plan {
    public stockMarket.MessageSell ev;
    public stockMarket.FindAndTellInvesters tev;
    public stockMarket.NewCompanyShares nsev;
    public aos.jack.util.thread.Semaphore mutex2;
    private static aos.jack.jak.plan.ExMap[] __exMap_body;
    private static java.lang.String[] __tt__body = {
            "stockMarket/HandleSellRequest.plan",
            "body",
            "36",
            "37",
            "33"};
    private final static java.lang.String[] __planVariableNames = {
            "ev",
            "tev",
            "nsev",
            "mutex2"};
    private final static java.lang.String[] __planVariableTypes = {
            "stockMarket.MessageSell",
            "stockMarket.FindAndTellInvesters",
            "stockMarket.NewCompanyShares",
            "Semaphore"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    static boolean relevant(stockMarket.MessageSell ev)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public HandleSellRequest()
    {
    }
    
    private HandleSellRequest(aos.jack.jak.task.Task __t, stockMarket.HandleSellRequest __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        ev = __env.ev;
        tev = __env.tev;
        nsev = __env.nsev;
        mutex2 = __env.mutex2;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        ev = (stockMarket.MessageSell) __a.findEvent("stockMarket.MessageSell");
        if (ev == null) {
            warning("Failed to find MessageSell ev");
            return false;
        }
        tev = (stockMarket.FindAndTellInvesters) __a.findEvent("stockMarket.FindAndTellInvesters");
        if (tev == null) {
            warning("Failed to find FindAndTellInvesters tev");
            return false;
        }
        nsev = (stockMarket.NewCompanyShares) __a.findEvent("stockMarket.NewCompanyShares");
        if (nsev == null) {
            warning("Failed to find NewCompanyShares nsev");
            return false;
        }
        mutex2 = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex2","aos.jack.util.thread.Semaphore",0);
        if (mutex2 == null) {
            warning("Failed to find Semaphore mutex2");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new stockMarket.HandleSellRequest.__bodyFSM();
    }
    
    private HandleSellRequest(stockMarket.MessageSell __ev, aos.jack.jak.task.Task __t, stockMarket.HandleSellRequest __env)
    {
        this(__t,__env);
        this.ev = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return ev.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "stockMarket.MessageSell";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((stockMarket.MessageSell) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof stockMarket.MessageSell)) 
            return null;
        stockMarket.MessageSell __e1 = (stockMarket.MessageSell) __e;
        return new stockMarket.HandleSellRequest(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(ev);
            }
            case 1: 
            {
                return aos.util.ToObject.box(tev);
            }
            case 2: 
            {
                return aos.util.ToObject.box(nsev);
            }
            case 3: 
            {
                return aos.util.ToObject.box(mutex2);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-HandleSellRequest.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(stockMarket.HandleSellRequest.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("HandleSellRequest.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (36)         @subtask(nsev.addNewCompanyShare(ev.company,ev.price,ev.numberOfShares));
                        case 10: 
                        {
                            __breakLevel = 0;
                            __task.push(nsev.addNewCompanyShare(ev.company,ev.price,ev.numberOfShares));
                            __state = -__state;
                            __subtask_pass = 11;
                            __subtask_fail = 4;
                            return SUBTASK;
                        }
                        //* (37)         @subtask(tev.findAllInvestors(ev.company,ev.price,ev.numberOfShares,ev.from));
                        case 11: 
                        {
                            __task.push(tev.findAllInvestors(ev.company,ev.price,ev.numberOfShares,ev.from));
                            __state = -__state;
                            __subtask_pass = 12;
                            __subtask_fail = 4;
                            return SUBTASK;
                        }
                        //* (33)     #reasoning method
                        case 12: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return stockMarket.HandleSellRequest.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("stockMarket.HandleSellRequest.body");
        }
        
    }
}
