/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package stockMarket;
import aos.jack.jak.core.Jak;
import aos.jack.jak.event.EventRecipient;
import aos.jack.jak.beliefset.OpenWorld;
import aos.jack.jak.beliefset.OpenWorldCursor;
import aos.jack.jak.beliefset.BeliefSetCursor;
import aos.jack.jak.beliefset.BeliefSetException;
import aos.jack.jak.beliefset.Tuple;
import aos.jack.jak.beliefset.BeliefSet;
import aos.jack.jak.logic.ChoicePoint;
import aos.jack.jak.logic.Variable;
import aos.jack.jak.cursor.BeliefState;
import aos.jack.jak.cursor.Cursor;

/**
this contains companies and the number of shares available to sell.
*/

public class OrderBook extends aos.jack.jak.beliefset.OpenWorld {
    static public stockMarket.OrderBook__Tuple __hole = new stockMarket.OrderBook__Tuple(true);
    public stockMarket.OrderBook__Tuple[][] __tables;
    public java.lang.String getDocumentation()
    {
        return "/**\nthis contains companies and the number of shares available to sell.\n*/\n";
    }
    
    public boolean attach(aos.jack.jak.event.EventRecipient __h)
    {
        java.lang.Object __o = __h;
        if (!super.attach(__h)) 
            return false;
        return true;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor getDetails(java.lang.String __v0, aos.jack.jak.logic.IntegerVariable __v1, aos.jack.jak.logic.IntegerVariable __v2)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        stockMarket.OrderBook__Tuple __t = new stockMarket.OrderBook__Tuple();
        stockMarket.OrderBook.__Cursor __c = new stockMarket.OrderBook.__Cursor(__t);
        __t.companyName = __v0;
        if (!__v1.check_unifiable(java.lang.Integer.TYPE)) 
            throw new aos.jack.jak.beliefset.BeliefSetException("OrderBook:getDetails:IOO: arg 1 numberOfShares Incorrect Variable type");
        if (__v1.isGround()) {
            try {
                __t.numberOfShares = __v1.as_int();
            }
            catch (java.lang.Exception e) {
                throw new aos.jack.jak.beliefset.BeliefSetException("OrderBook:getDetails:IOO: got " + e.toString());
            }
        }
         else 
            __c.numberOfShares = __v1;
        if (!__v2.check_unifiable(java.lang.Integer.TYPE)) 
            throw new aos.jack.jak.beliefset.BeliefSetException("OrderBook:getDetails:IOO: arg 2 sharePrice Incorrect Variable type");
        if (__v2.isGround()) {
            try {
                __t.sharePrice = __v2.as_int();
            }
            catch (java.lang.Exception e) {
                throw new aos.jack.jak.beliefset.BeliefSetException("OrderBook:getDetails:IOO: got " + e.toString());
            }
        }
         else 
            __c.sharePrice = __v2;
        __c.init(1,this);
        return __c;
    }
    
    public int keyIndex()
    {
        return 0;
    }
    
    public int fullIndex()
    {
        return 1;
    }
    
    public int nIndexes()
    {
        return 2;
    }
    
    public aos.jack.jak.beliefset.Tuple newTuple()
    {
        return new stockMarket.OrderBook__Tuple();
    }
    
    public aos.jack.jak.beliefset.Tuple getTuple(int t, int l)
    {
        return __tables[t][l];
    }
    
    public aos.jack.jak.beliefset.Tuple[] newTable(int t)
    {
        return new stockMarket.OrderBook__Tuple[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] newTables(int t)
    {
        return new stockMarket.OrderBook__Tuple[t][];
    }
    
    public aos.jack.jak.beliefset.Tuple[] getTable(int t)
    {
        return __tables[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] getTables()
    {
        return __tables;
    }
    
    public void setTables(aos.jack.jak.beliefset.Tuple[][] t)
    {
        __tables = (stockMarket.OrderBook__Tuple[][]) t;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor newCursor(aos.jack.jak.beliefset.Tuple __t)
    {
        if (__t instanceof stockMarket.OrderBook__Tuple) 
            return new stockMarket.OrderBook.__Cursor((stockMarket.OrderBook__Tuple) __t);
        return null;
    }
    
    public void add(java.lang.String __v0, int __v1, int __v2)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        add(__v0,__v1,__v2,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void add(java.lang.String __v0, int __v1, int __v2, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        stockMarket.OrderBook__Tuple __t = new stockMarket.OrderBook__Tuple();
        __t.companyName = __v0;
        __t.numberOfShares = __v1;
        __t.sharePrice = __v2;
        super.assertTuple(__t,__d);
    }
    
    public void remove(java.lang.String __v0, int __v1, int __v2)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        remove(__v0,__v1,__v2,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void remove(java.lang.String __v0, int __v1, int __v2, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        stockMarket.OrderBook__Tuple __t = new stockMarket.OrderBook__Tuple();
        __t.companyName = __v0;
        __t.numberOfShares = __v1;
        __t.sharePrice = __v2;
        super.retractTuple(__t,__d);
    }
    
    public OrderBook()
    {
    }
    
    public OrderBook(java.lang.String n)
    {
        super();
        read(n);
    }
    
    class __Cursor extends aos.jack.jak.beliefset.OpenWorldCursor {
        public stockMarket.OrderBook__Tuple __tuple = null;
        public aos.jack.jak.logic.Variable companyName;
        public aos.jack.jak.logic.Variable numberOfShares;
        public aos.jack.jak.logic.Variable sharePrice;
        public __Cursor()
        {
            __tuple = __hole;
        }
        
        public __Cursor(stockMarket.OrderBook__Tuple __t)
        {
            super();
            __tuple = __t;
        }
        
        public int match(int __ti, int __st, int __c, boolean __k, int __ind)
        {
            stockMarket.OrderBook__Tuple[] __tab = __tables[__ti];
            stockMarket.OrderBook__Tuple __t;
            int __sz = __tab.length;
            int __i;
            if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) {
                aos.jack.jak.core.Jak.log.log("OrderBook__Tuple:match:" + __ti + ":" + __st + ":" + __c + ":" + __k + ":" + __ind);
                aos.jack.jak.core.Jak.log.log("Tuple=" + __tuple);
                aos.jack.jak.core.Jak.log.log("Outputs are");
                aos.jack.jak.core.Jak.log.log("  companyName:" + companyName);
                aos.jack.jak.core.Jak.log.log("  numberOfShares:" + numberOfShares);
                aos.jack.jak.core.Jak.log.log("  sharePrice:" + sharePrice);
            }
            for (__i = __st; __c > 0; __i = (__i + 1) % __sz, __c-- ) {
                __t = __tab[__i];
                if (__t == null) {
                    if (__ind < 0) 
                        continue;
                    return -1;
                }
                if (__t == __hole) 
                    continue;
                if (__t.isFree) {
                    __tab[__i] = __hole;
                    continue;
                }
                if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) 
                    aos.jack.jak.core.Jak.log.log("t" + __i + ":" + __t);
                try {
                    if (cp != null) 
                        cp.backtrack();
                    if (__k) 
                        return __i;
                    if (companyName == null) {
                        if (!__tuple.companyName.equals(__t.companyName)) 
                            continue;
                    }
                     else {
                        if (!companyName.unify(__t.companyName)) 
                            continue;
                    }
                    if (numberOfShares == null) {
                        if (__tuple.numberOfShares != __t.numberOfShares) 
                            continue;
                    }
                     else {
                        if (!numberOfShares.unify(__t.numberOfShares)) 
                            continue;
                    }
                    if (sharePrice == null) {
                        if (__tuple.sharePrice != __t.sharePrice) 
                            continue;
                    }
                     else {
                        if (!sharePrice.unify(__t.sharePrice)) 
                            continue;
                    }
                }
                catch (java.lang.Exception e) {
                    continue;
                }
                return __i;
            }
            return -1;
        }
        
        public int hash(int __i)
        {
            return (__tuple == null?0:__tuple.hash(__i));
        }
        
        public aos.jack.jak.logic.ChoicePoint getChoicePoint()
        {
            if (companyName != null) 
                return companyName.getEnv().newChoicePoint();
            if (numberOfShares != null) 
                return numberOfShares.getEnv().newChoicePoint();
            if (sharePrice != null) 
                return sharePrice.getEnv().newChoicePoint();
            return null;
        }
        
        public boolean isKeyGround()
        {
            return true;
        }
        
    }
}
